name: "Upload ici workspace"
description: "Upload the ici workspace as a tarball artifact"
inputs:
  basedir:
    description: "ICI $BASEDIR"
    required: false
    default: $BASEDIR
  subdir:
    description: "sub folder of workspace"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: Create tarball
      shell: bash
      run: |
        cd ${{ inputs.basedir }}/${{ inputs.subdir }}
        tar czf /tmp/ici.tar.gz .
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ici-workspace
        path: /tmp/ici.tar.gz
